workflows:
  # ios-release:
  #   ...

  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      # groups:
      #   - google_play_credentials
      vars:
        PACKAGE_NAME: "com.ooinkramen.ooink"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android app bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab