// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWTa8Ps2nWUaZuSGQDPrTlQ7u-gJ_xcxA',
    appId: '1:352871490538:android:1c089c26231437bc374893',
    messagingSenderId: '352871490538',
    projectId: 'ooinkai',
    storageBucket: 'ooinkai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzUhZCYZaN1RWMaBebNE3WR3Ime8wq5IM',
    appId: '1:352871490538:ios:e22ac75410110472374893',
    messagingSenderId: '352871490538',
    projectId: 'ooinkai',
    storageBucket: 'ooinkai.firebasestorage.app',
    iosBundleId: 'com.ooinkramen.ooink',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX08ybdxlEciYwBTDxpdz0g-wAdU0pFxY',
    appId: '1:352871490538:web:5d8aaa32b028f446374893',
    messagingSenderId: '352871490538',
    projectId: 'ooinkai',
    authDomain: 'ooinkai.firebaseapp.com',
    storageBucket: 'ooinkai.firebasestorage.app',
    measurementId: 'G-N6EJ5J4ZVN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzUhZCYZaN1RWMaBebNE3WR3Ime8wq5IM',
    appId: '1:352871490538:ios:d1e4e0451f13c028374893',
    messagingSenderId: '352871490538',
    projectId: 'ooinkai',
    storageBucket: 'ooinkai.firebasestorage.app',
    iosBundleId: 'com.ooinkai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX08ybdxlEciYwBTDxpdz0g-wAdU0pFxY',
    appId: '1:352871490538:web:947cd095c0055dc8374893',
    messagingSenderId: '352871490538',
    projectId: 'ooinkai',
    authDomain: 'ooinkai.firebaseapp.com',
    storageBucket: 'ooinkai.firebasestorage.app',
    measurementId: 'G-WM8VQG1FY7',
  );

}